import { MAIN_CATEGORIES } from './constants';

export interface FallbackAuthor {
  id: string;
  name: string;
  nameBn: string;
  slug: string;
  avatar: string;
  designation: string;
  designationBn: string;
}

export interface FallbackCategory {
  id: string;
  name: string;
  nameBn: string;
  slug: string;
  color?: string;
}

export const FALLBACK_AUTHORS: FallbackAuthor[] = [
  {
    id: 'auth-1',
    name: 'Dr. Rafiqul Islam',
    nameBn: 'ড. রফিকুল ইসলাম',
    slug: 'dr-rafiqul-islam',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    designation: 'Editor-in-Chief',
    designationBn: 'প্রধান সম্পাদক',
  },
  {
    id: 'auth-2',
    name: 'Nazneen Sultana',
    nameBn: 'নাজনীন সুলতানা',
    slug: 'nazneen-sultana',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    designation: 'Executive Editor',
    designationBn: 'নির্বাহী সম্পাদক',
  },
  {
    id: 'auth-3',
    name: 'Tanvir Ahmed',
    nameBn: 'তানভীর আহমেদ',
    slug: 'tanvir-ahmed',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    designation: 'Staff Reporter',
    designationBn: 'স্টাফ রিপোর্টার',
  },
];

export const FALLBACK_CATEGORIES: FallbackCategory[] = MAIN_CATEGORIES.map((c, i) => ({
  id: `cat-${c.slug}`,
  name: c.name,
  nameBn: c.nameBn,
  slug: c.slug,
  color: '#1E3E62',
}));

export const FALLBACK_ARTICLES: any[] = [
  {
    id: 'art-1',
    title: 'জাতীয় অর্থনৈতিক রূপরেখা ও আধুনিক অবকাঠামো উন্নয়ন: নতুন মেগা প্রকল্পের অনুমোদন একনেকে',
    titleBn: 'জাতীয় অর্থনৈতিক রূপরেখা ও আধুনিক অবকাঠামো উন্নয়ন: নতুন মেগা প্রকল্পের অনুমোদন একনেকে',
    slug: 'national-economic-roadmap-mega-projects-approved-ecnec',
    subtitle: 'যোগাযোগ ও জ্বালানি খাতের সংস্কারে অগ্রাধিকার, বাস্তবায়নে থাকছে বিশেষ মনিটরিং সেল',
    excerpt: 'দেশের সার্বিক অর্থনৈতিক প্রবৃদ্ধি ত্বরান্বিত করতে এবং আঞ্চলিক যোগাযোগ ব্যবস্থা জোরদার করতে ১০টি নতুন উন্নয়ন প্রকল্পের চূড়ান্ত অনুমোদন দিয়েছে জাতীয় অর্থনৈতিক পরিষদের নির্বাহী কমিটি (একনেক)।',
    content: `<p class="lead">দেশের সার্বিক অর্থনৈতিক প্রবৃদ্ধি ত্বরান্বিত করতে এবং আঞ্চলিক যোগাযোগ ব্যবস্থা জোরদার করতে প্রায় ১২ হাজার কোটি টাকা ব্যয়ে ১০টি নতুন উন্নয়ন প্রকল্পের চূড়ান্ত অনুমোদন দিয়েছে জাতীয় অর্থনৈতিক পরিষদের নির্বাহী কমিটি (একনেক)।</p>
    <h3>প্রকল্পের অগ্রাধিকার খাতসমূহ</h3>
    <p>সভায় জানানো হয়, অনুমোদিত প্রকল্পগুলোর মধ্যে রেল ও সড়ক নেটওয়ার্ক সম্প্রসারণ, নবায়নযোগ্য জ্বালানি উৎপাদন এবং আধুনিক কৃষি সেচ প্রযুক্তি স্থাপন শীর্ষে রয়েছে।</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=1200&auto=format&fit=crop&q=80',
    imageCaption: 'একনেক সভায় গুরুত্বপূর্ণ উন্নয়ন প্রকল্পের চূড়ান্ত পর্যালোচনা। ছবি: স্ট্যাটবাউন্ড ডেস্ক',
    photographerCredit: 'স্ট্যাটবাউন্ড ব্যুরো',
    categoryId: 'cat-national',
    category: { id: 'cat-national', name: 'National', nameBn: 'জাতীয়', slug: 'national', color: '#1E3E62' },
    authorId: 'auth-1',
    author: FALLBACK_AUTHORS[0],
    tags: 'জাতীয়, একনেক, অর্থনীতি, উন্নয়ন, মেগা প্রকল্প, বাংলাদেশ',
    status: 'PUBLISHED',
    isHero: true,
    isFeatured: true,
    isTrending: true,
    isBreaking: true,
    viewsCount: 6540,
    readTimeMinutes: 4,
    publishedAt: new Date(Date.now() - 1000 * 60 * 5),
    createdAt: new Date(Date.now() - 1000 * 60 * 5),
  },
  {
    id: 'art-2',
    title: 'নতুন আধুনিক শিক্ষা কাঠামো ঘোষণা: ডিজিটাল দক্ষতা ও সৃজনশীলতায় বিশেষ জোর',
    titleBn: 'নতুন আধুনিক শিক্ষা কাঠামো ঘোষণা: ডিজিটাল দক্ষতা ও সৃজনশীলতায় বিশেষ জোর',
    slug: 'new-education-framework-digital-skills-announced',
    subtitle: 'আগামী শিক্ষাবর্ষ থেকেই প্রাথমিক ও মাধ্যমিকে নতুন পাঠ্যসূচি ও মূল্যায়ন ব্যবস্থা কার্যকর হচ্ছে',
    excerpt: 'দেশের শিক্ষাব্যবস্থাকে যুগোপযোগী ও বৈশ্বিক মানসম্পন্ন করতে নতুন আধুনিক পাঠ্যক্রম এবং মূল্যায়ন কাঠামোর পূর্ণাঙ্গ রূপরেখা আনুষ্ঠানিকভাবে ঘোষণা করেছে শিক্ষা মন্ত্রণালয়।',
    content: `<p class="lead">দেশের শিক্ষাব্যবস্থাকে যুগোপযোগী ও বৈশ্বিক মানসম্পন্ন করতে নতুন আধুনিক পাঠ্যক্রম এবং মূল্যায়ন কাঠামোর পূর্ণাঙ্গ রূপরেখা ঘোষণা করা হয়েছে।</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=80',
    imageCaption: 'রাজধানীর একটি আধুনিক ডিজিটাল ক্লাসরুমে শিক্ষার্থীদের সক্রিয় পাঠদান কার্যক্রম। ছবি: স্ট্যাটবাউন্ড নিউজ',
    photographerCredit: 'আহসান হাবীব / স্ট্যাটবাউন্ড নিউজ',
    categoryId: 'cat-education',
    category: { id: 'cat-education', name: 'Education', nameBn: 'শিক্ষা', slug: 'education', color: '#059669' },
    authorId: 'auth-3',
    author: FALLBACK_AUTHORS[2],
    tags: 'শিক্ষা, ডিজিটাল দক্ষতা, পাঠ্যক্রম, শিক্ষা মন্ত্রণালয়, বাংলাদেশ',
    status: 'PUBLISHED',
    isHero: false,
    isFeatured: true,
    isTrending: true,
    isBreaking: false,
    viewsCount: 4210,
    readTimeMinutes: 4,
    publishedAt: new Date(Date.now() - 1000 * 60 * 18),
    createdAt: new Date(Date.now() - 1000 * 60 * 18),
  },
  {
    id: 'art-3',
    title: 'চট্টগ্রাম বন্দরে রেকর্ড কনটেইনার হ্যান্ডলিং: অর্থনৈতিক বাণিজ্যে নতুন গতি সঞ্চার',
    titleBn: 'চট্টগ্রাম বন্দরে রেকর্ড কনটেইনার হ্যান্ডলিং: অর্থনৈতিক বাণিজ্যে নতুন গতি সঞ্চার',
    slug: 'chattogram-port-record-container-handling-growth',
    subtitle: 'স্বয়ংক্রিয় টার্মিনাল অপারেশন ও আধুনিক স্ক্যানিং প্রযুক্তিতে সময় সাশ্রয় হয়েছে দ্বিগুণ',
    excerpt: 'চট্টগ্রাম সমুদ্রবন্দরে চলতি অর্থবছরে কনটেইনার ও কার্গো হ্যান্ডলিংয়ে নতুন ঐতিহাসিক রেকর্ড সৃষ্টি হয়েছে। অটোমেশনের সুফল পেতে শুরু করেছে দেশের রপ্তানিমুখী তৈরি পোশাক ও শিল্প খাত।',
    content: `<p>চট্টগ্রাম সমুদ্রবন্দরে চলতি অর্থবছরে কনটেইনার ও কার্গো হ্যান্ডলিংয়ে নতুন ঐতিহাসিক রেকর্ড সৃষ্টি হয়েছে।</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=1200&auto=format&fit=crop&q=80',
    imageCaption: 'চট্টগ্রাম বন্দরের আধুনিক টার্মিনালে পণ্য ওঠানামা কার্যক্রম। ছবি: স্ট্যাটবাউন্ড',
    photographerCredit: 'সুমন দাশ / স্ট্যাটবাউন্ড',
    categoryId: 'cat-chattogram',
    category: { id: 'cat-chattogram', name: 'Chattogram', nameBn: 'চট্টগ্রাম', slug: 'chattogram', color: '#0891B2' },
    authorId: 'auth-1',
    author: FALLBACK_AUTHORS[0],
    tags: 'চট্টগ্রাম, বন্দর, বাণিজ্য, অর্থনীতি, রপ্তানি',
    status: 'PUBLISHED',
    isFeatured: true,
    isTrending: true,
    viewsCount: 3120,
    readTimeMinutes: 3,
    publishedAt: new Date(Date.now() - 1000 * 60 * 35),
    createdAt: new Date(Date.now() - 1000 * 60 * 35),
  },
  {
    id: 'art-4',
    title: 'হাইটেক পার্কে তৈরি হচ্ছে কৃত্রিম বুদ্ধিমত্তা ও সেমিকন্ডাক্টর হাব: বিপুল কর্মসংস্থানের আশা',
    titleBn: 'হাইটেক পার্কে তৈরি হচ্ছে কৃত্রিম বুদ্ধিমত্তা ও সেমিকন্ডাক্টর হাব: বিপুল কর্মসংস্থানের আশা',
    slug: 'hightech-park-ai-semiconductor-hub-employment',
    subtitle: '৫০টি বৈশ্বিক ও দেশীয় প্রযুক্তি প্রতিষ্ঠান যৌথ বিনিয়োগে আসছে',
    excerpt: 'তথ্যপ্রযুক্তি খাতে দেশকে পরবর্তী ধাপে নিয়ে যেতে কালিয়াকৈর হাইটেক পার্কে গড়ে তোলা হচ্ছে অত্যাধুনিক এআই গবেষণা কেন্দ্র ও চিপ ডিজাইনিং ল্যাব।',
    content: `<p>দেশের সফটওয়্যার ও হার্ডওয়্যার উদ্ভাবনকে বৈশ্বিক মানে উন্নীত করতে গাজীপুরের কালিয়াকৈর হাইটেক পার্কে একটি পূর্ণাঙ্গ কৃত্রিম বুদ্ধিমত্তা (AI) ও সেমিকন্ডাক্টর ডিজাইন হাব গড়ে তোলার চুক্তি সম্পন্ন হয়েছে।</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&auto=format&fit=crop&q=80',
    imageCaption: 'প্রযুক্তি গবেষণা ল্যাবরেটরিতে মাইক্রোচিপ ডিজাইনে কর্মরত প্রকৌশলীরা।',
    photographerCredit: 'তানভীর রশীদ',
    categoryId: 'cat-technology',
    category: { id: 'cat-technology', name: 'Technology', nameBn: 'প্রযুক্তি', slug: 'technology', color: '#0284C7' },
    authorId: 'auth-3',
    author: FALLBACK_AUTHORS[2],
    tags: 'প্রযুক্তি, কৃত্রিম বুদ্ধিমত্তা, সেমিকন্ডাক্টর, হাইটেক পার্ক, চাকরি',
    status: 'PUBLISHED',
    isFeatured: true,
    isTrending: true,
    viewsCount: 2890,
    readTimeMinutes: 4,
    publishedAt: new Date(Date.now() - 1000 * 60 * 55),
    createdAt: new Date(Date.now() - 1000 * 60 * 55),
  },
  {
    id: 'art-5',
    title: 'জাতীয় নির্বাচনে আধুনিক স্বচ্ছতা ও সুষ্ঠু পরিবেশ নিশ্চিতে সব দলের সঙ্গে সংলাপের প্রস্তুতি',
    titleBn: 'জাতীয় নির্বাচনে আধুনিক স্বচ্ছতা ও সুষ্ঠু পরিবেশ নিশ্চিতে সব দলের সঙ্গে সংলাপের প্রস্তুতি',
    slug: 'national-election-dialogue-transparency-preparations',
    subtitle: 'নির্বাচন ব্যবস্থা সংস্কার কমিশন চূড়ান্ত সুপারিশমালা পেশ করেছে',
    excerpt: 'আসন্ন জাতীয় নির্বাচনকে নিরপেক্ষ, অবাধ ও সর্বজনীন গ্রহণযোগ্য করতে নির্বাচন ব্যবস্থা সংস্কার কমিশন তাদের বিস্তারিত সুপারিশ চূড়ান্ত করেছে।',
    content: `<p>নির্বাচন কমিশনের পুনর্গঠন ও আধুনিকায়নে গঠিত জাতীয় সংস্কার কমিশন তাদের পূর্ণাঙ্গ প্রতিবেদন প্রস্তুত করেছে।</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=1200&auto=format&fit=crop&q=80',
    imageCaption: 'নির্বাচন ব্যবস্থার আধুনিকায়ন নিয়ে পর্যালোচনা বৈঠক।',
    photographerCredit: 'স্ট্যাটবাউন্ড ব্যুরো',
    categoryId: 'cat-politics',
    category: { id: 'cat-politics', name: 'Politics', nameBn: 'রাজনীতি', slug: 'politics', color: '#DC2626' },
    authorId: 'auth-2',
    author: FALLBACK_AUTHORS[1],
    tags: 'রাজনীতি, জাতীয় নির্বাচন, নির্বাচন কমিশন, সংলাপ',
    status: 'PUBLISHED',
    isFeatured: true,
    viewsCount: 3840,
    readTimeMinutes: 3,
    publishedAt: new Date(Date.now() - 1000 * 60 * 90),
    createdAt: new Date(Date.now() - 1000 * 60 * 90),
  },
  {
    id: 'art-6',
    title: 'বাংলাদেশ প্রিমিয়ার লিগে তরুণদের চমক: রোমাঞ্চকর ম্যাচে জয় তুলে নিল চট্টগ্রাম ভাইকিংস',
    titleBn: 'বাংলাদেশ প্রিমিয়ার লিগে তরুণদের চমক: রোমাঞ্চকর ম্যাচে জয় তুলে নিল চট্টগ্রাম ভাইকিংস',
    slug: 'bpl-cricket-thrilling-match-chattogram-victory',
    subtitle: 'শেষ ওভারের টানটান উত্তেজনায় ৩ উইকেটের রুদ্ধশ্বাস জয়',
    excerpt: 'জহুর আহমেদ চৌধুরী স্টেডিয়ামে অনুষ্ঠিত বিপিএলের হাই-ভোল্টেজ ম্যাচে শেষ বলের ছক্কায় স্মরণীয় জয় ছিনিয়ে নিয়েছে স্বাগতিক চট্টগ্রাম।',
    content: `<p>চট্টগ্রামের জহুর আহমেদ চৌধুরী স্টেডিয়ামে দর্শকদের হৃদয়স্পন্দন বাড়িয়ে দেওয়া এক ম্যাচে শেষ বলের নাটকীয়তায় জয় পেয়েছে চট্টগ্রাম ভাইকিংস।</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1531415074868-036b1c57e3ce?w=1200&auto=format&fit=crop&q=80',
    imageCaption: 'ম্যাচ জয়ের পর খেলোয়াড়দের আনন্দ উদযাপন। ছবি: স্ট্যাটবাউন্ড স্পোর্টস',
    photographerCredit: 'মেহজাবীন চৌধুরী',
    categoryId: 'cat-sports',
    category: { id: 'cat-sports', name: 'Sports', nameBn: 'খেলাধুলা', slug: 'sports', color: '#16A34A' },
    authorId: 'auth-3',
    author: FALLBACK_AUTHORS[2],
    tags: 'খেলাধুলা, ক্রিকেট, বিপিএল, চট্টগ্রাম, জয়',
    status: 'PUBLISHED',
    isFeatured: true,
    isTrending: true,
    viewsCount: 5200,
    readTimeMinutes: 3,
    publishedAt: new Date(Date.now() - 1000 * 60 * 120),
    createdAt: new Date(Date.now() - 1000 * 60 * 120),
  },
  {
    id: 'art-7',
    title: 'বাংলাদেশ ব্যাংকের বৈদেশিক মুদ্রা রিজার্ভে স্বস্তি: রেমিট্যান্স ও রপ্তানি আয়ে উল্লেখযোগ্য প্রবৃদ্ধি',
    titleBn: 'বাংলাদেশ ব্যাংকের বৈদেশিক মুদ্রা রিজার্ভে স্বস্তি: রেমিট্যান্স ও রপ্তানি আয়ে উল্লেখযোগ্য প্রবৃদ্ধি',
    slug: 'central-bank-forex-reserves-growth-remittance',
    subtitle: 'প্রবাসী আয়ে ২৫ শতাংশ প্রবৃদ্ধি, ব্যাংকিং চ্যানেলে অর্থ পাঠাতে বিশেষ প্রণোদনা বৃদ্ধি',
    excerpt: 'বৈধ ব্যাংকিং চ্যানেলে রেমিট্যান্স প্রবাহ বৃদ্ধি এবং রপ্তানি আয় ইতিবাচক ধারায় থাকায় বাংলাদেশ ব্যাংকের গ্রস বৈদেশিক মুদ্রার রিজার্ভ ২৫ বিলিয়ন ডলার অতিক্রম করেছে।',
    content: `<p>বৈধ ব্যাংকিং চ্যানেলে রেমিট্যান্স প্রবাহ বৃদ্ধি এবং রপ্তানি আয় ইতিবাচক ধারায় থাকায় বাংলাদেশ ব্যাংকের বৈদেশিক মুদ্রার রিজার্ভে ইতিবাচক গতি লক্ষ্য করা গেছে।</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=1200&auto=format&fit=crop&q=80',
    imageCaption: 'বাংলাদেশ ব্যাংক ভবন। ছবি: সংগৃহীত',
    photographerCredit: 'অর্থনীতি ডেস্ক',
    categoryId: 'cat-business',
    category: { id: 'cat-business', name: 'Business', nameBn: 'ব্যবসা', slug: 'business', color: '#4F46E5' },
    authorId: 'auth-1',
    author: FALLBACK_AUTHORS[0],
    tags: 'ব্যবসা, ব্যাংক, রেমিট্যান্স, রিজার্ভ, অর্থনীতি',
    status: 'PUBLISHED',
    isFeatured: true,
    viewsCount: 4100,
    readTimeMinutes: 3,
    publishedAt: new Date(Date.now() - 1000 * 60 * 150),
    createdAt: new Date(Date.now() - 1000 * 60 * 150),
  },
  {
    id: 'art-8',
    title: 'ঢাকায় আধুনিক বায়ুমান পর্যবেক্ষণ কেন্দ্র স্থাপন: পরিবেশ দূষণ নিয়ন্ত্রণে সমন্বিত মহাপরিকল্পনা',
    titleBn: 'ঢাকায় আধুনিক বায়ুমান পর্যবেক্ষণ কেন্দ্র স্থাপন: পরিবেশ দূষণ নিয়ন্ত্রণে সমন্বিত মহাপরিকল্পনা',
    slug: 'dhaka-air-quality-monitoring-stations-plan',
    subtitle: 'রাজধানীর ২০টি পয়েন্টে রিয়েল-টাইম ডিসপ্লে ও সেন্সর নেটওয়ার্ক স্থাপন শুরু',
    excerpt: 'রাজধানী ঢাকা ও পার্শ্ববর্তী এলাকার বায়ুদূষণ নিয়ন্ত্রণ ও সার্বক্ষণিক পর্যবেক্ষণ নিশ্চিত করতে আধুনিক এআই-চালিত ২০টি নতুন এয়ার কোয়ালিটি মনিটরিং স্টেশন স্থাপন করা হচ্ছে।',
    content: `<p>রাজধানীর বায়ুর মান উন্নয়নে আধুনিক পরিবেশ মনিটরিং ব্যবস্থা স্থাপন শুরু হয়েছে।</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=1200&auto=format&fit=crop&q=80',
    imageCaption: 'পরিবেশ ও আবহাওয়া পর্যবেক্ষণ কেন্দ্র।',
    photographerCredit: 'পরিবেশ ডেস্ক',
    categoryId: 'cat-national',
    category: { id: 'cat-national', name: 'National', nameBn: 'জাতীয়', slug: 'national', color: '#1E3E62' },
    authorId: 'auth-2',
    author: FALLBACK_AUTHORS[1],
    tags: 'জাতীয়, পরিবেশ, বায়ুদূষণ, ঢাকা, আবহাওয়া',
    status: 'PUBLISHED',
    viewsCount: 1950,
    readTimeMinutes: 3,
    publishedAt: new Date(Date.now() - 1000 * 60 * 180),
    createdAt: new Date(Date.now() - 1000 * 60 * 180),
  },
];

export const FALLBACK_BREAKING_NEWS = [
  { id: 'bn-1', headline: 'জাতীয় অর্থনৈতিক পরিষদের সভায় ১০টি নতুন মেগা প্রকল্পের চূড়ান্ত অনুমোদন', priority: 1 },
  { id: 'bn-2', headline: 'বাংলাদেশ ব্যাংকের বৈদেশিক মুদ্রা রিজার্ভ ২৫ বিলিয়ন ডলার অতিক্রম', priority: 2 },
  { id: 'bn-3', headline: 'চট্টগ্রাম বন্দরে কনটেইনার হ্যান্ডলিংয়ে নতুন ঐতিহাসিক রেকর্ড', priority: 3 },
];

export const FALLBACK_VIDEOS = [
  {
    id: 'vid-1',
    title: 'পদ্মা সেতু ও আধুনিক রেল সংযোগে বদলে যাওয়া দক্ষিণবঙ্গের অর্থনীতি',
    titleBn: 'পদ্মা সেতু ও আধুনিক রেল সংযোগে বদলে যাওয়া দক্ষিণবঙ্গের অর্থনীতি',
    slug: 'padma-bridge-rail-impact-documentary',
    thumbnailUrl: 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800&auto=format&fit=crop&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    duration: '০৫:২০',
    viewsCount: 14200,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: 'vid-2',
    title: 'বিপিএল ক্রিকেট ২০২৬: চট্টগ্রাম ভাইকিংসের নাটকীয় শেষ ওভারের রোমাঞ্চকর জয়',
    titleBn: 'বিপিএল ক্রিকেট ২০২৬: চট্টগ্রাম ভাইকিংসের নাটকীয় শেষ ওভারের রোমাঞ্চকর জয়',
    slug: 'bpl-cricket-thrilling-match-highlights',
    thumbnailUrl: 'https://images.unsplash.com/photo-1531415074868-036b1c57e3ce?w=800&auto=format&fit=crop&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    duration: '০৪:১৫',
    viewsCount: 22800,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
  },
];

export const FALLBACK_GALLERIES = [
  {
    id: 'gal-1',
    title: 'বসন্তে রঙিন ঢাকা: ফুলে ফুলে সেজেছে রাজধানীর রাজপথ ও উদ্যান',
    titleBn: 'বসন্তে রঙিন ঢাকা: ফুলে ফুলে সেজেছে রাজধানীর রাজপথ ও উদ্যান',
    slug: 'spring-colors-dhaka-photo-story',
    coverImage: 'https://images.unsplash.com/photo-1588600878108-578307a3cc9d?w=800&auto=format&fit=crop&q=80',
    photographerCredit: 'আহসান হাবীব / স্ট্যাটবাউন্ড',
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 3),
    images: [
      { id: 'gimg-1', imageUrl: 'https://images.unsplash.com/photo-1588600878108-578307a3cc9d?w=800&auto=format&fit=crop&q=80', caption: 'বসন্তের রক্তিম পলাশ ও শিমুল' },
      { id: 'gimg-2', imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&auto=format&fit=crop&q=80', caption: 'ক্যাম্পাসে তরুণদের উৎসব' },
    ],
  },
];
